Repository TeamJupoza/Jupoza, pull requests merged in 2023-03, with the labels that each got.

#29 #28 - DB erd , repository 및 테스트 정의
  build.gradle
  document/.$jupoza-erd.svg.bkp
  document/jupoza-erd.svg
  src/main/java/gachon/jupoza/domain/Stock.java
  src/main/java/gachon/jupoza/repository/ArticleCommentRepository.java
  src/main/java/gachon/jupoza/repository/ArticleRepository.java
  src/main/java/gachon/jupoza/repository/PortfolioRepository.java
  src/main/java/gachon/jupoza/repository/StockRepository.java
  src/main/java/gachon/jupoza/repository/UserAccountRepository.java
  src/main/java/gachon/jupoza/repository/weightsRepository.java
  src/main/resources/application.yaml
  src/test/java/gachon/jupoza/repository/JpaRepositoryTest.java
Labels: documentation, enhancement

#32 도메인 수정및 추가
  document/.$jupoza-erd.svg.bkp
  document/.$jupoza-erd.svg.dtmp
  document/jupoza-erd.svg
  src/main/java/gachon/jupoza/domain/PortFolio.java
  src/main/java/gachon/jupoza/domain/UserAccount.java
  src/main/java/gachon/jupoza/domain/weights.java
Labels: enhancement

#33 #31 - Weight 클래스 추가
  src/main/java/gachon/jupoza/domain/Weights.java
  src/main/java/gachon/jupoza/repository/WeightsRepository.java
Labels: enhancement

#34 #31 - 엔티티의 Dto 수정및 삭제
  src/main/java/gachon/jupoza/dto/PortfolioDTO.java
  src/main/java/gachon/jupoza/dto/StockDTO.java
  src/main/java/gachon/jupoza/dto/StockListDTO.java
  src/main/java/gachon/jupoza/dto/WeightsDto.java
Labels: enhancement

#35 Feature/#31 domain update
  src/main/java/gachon/jupoza/controller/MyPortfolioController.java
  src/main/java/gachon/jupoza/controller/StockController.java
  src/main/java/gachon/jupoza/controller/portFolioController.java
  src/main/java/gachon/jupoza/repository/PortfolioRepository.java
  src/main/java/gachon/jupoza/repository/WeightsRepository.java
  src/main/java/gachon/jupoza/service/MyPortfolioService.java
  src/main/java/gachon/jupoza/service/StockService.java
  src/main/java/gachon/jupoza/service/portFolioService.java
  src/test/java/gachon/jupoza/controller/MyPortfolioControllerTest.java
  src/test/java/gachon/jupoza/service/MyPortfolioServiceTest.java
Labels: enhancement

#36 #31 - 도메인 수정및 Dto 추가
  src/main/java/gachon/jupoza/domain/UserAccount.java
  src/main/java/gachon/jupoza/domain/Weights.java
  src/main/java/gachon/jupoza/dto/PortFolioDto.java
  src/main/java/gachon/jupoza/dto/StockDTO.java
  src/main/java/gachon/jupoza/dto/StockDto.java
  src/main/java/gachon/jupoza/dto/StockListDto.java
  src/main/java/gachon/jupoza/dto/UserAccountDto.java
  src/main/java/gachon/jupoza/dto/WeightsDto.java
Labels: enhancement

#37 #31 - 수정사항 업데이트
  src/main/java/gachon/jupoza/controller/portFolioController.java
  src/main/java/gachon/jupoza/domain/PortFolio.java
  src/main/java/gachon/jupoza/dto/PortFolioDto.java
  src/main/java/gachon/jupoza/service/MyPortfolioService.java
  src/main/java/gachon/jupoza/service/StockService.java
  src/main/java/gachon/jupoza/service/portFolioService.java
  src/test/java/gachon/jupoza/service/MyPortfolioServiceTest.java
Labels: enhancement

#38 Feature/#30 db test
  src/main/java/gachon/jupoza/domain/PortFolio.java
  src/main/java/gachon/jupoza/dto/PortFolioDto.java
  src/main/java/gachon/jupoza/dto/WeightsDto.java
  src/main/java/gachon/jupoza/repository/UserAccountRepository.java
  src/main/java/gachon/jupoza/service/MyPortfolioService.java
  src/main/resources/data.sql
  src/test/java/gachon/jupoza/repository/JpaRepositoryTest.java
  src/test/java/gachon/jupoza/service/MyPortfolioServiceTest.java
Labels: enhancement

#48 게시글, 게시판 구현
  document/.$jupoza-erd.svg.bkp
  document/.$jupoza-erd.svg.dtmp
  document/jupoza-erd.svg
  src/main/java/gachon/jupoza/controller/ArticleController.java
  src/main/java/gachon/jupoza/controller/MainController.java
  src/main/java/gachon/jupoza/domain/Article.java
  src/main/java/gachon/jupoza/domain/ArticleStock.java
  src/main/java/gachon/jupoza/dto/ArticleDto.java
  src/main/java/gachon/jupoza/dto/Request/ArticleRequest.java
  src/main/java/gachon/jupoza/dto/Response/ArticleResponse.java
  src/main/java/gachon/jupoza/repository/ArticleRepository.java
  src/main/java/gachon/jupoza/repository/ArticleStockRepository.java
  src/main/java/gachon/jupoza/repository/MyStockRepository.java
  src/main/java/gachon/jupoza/repository/UserAccountRepository.java
  src/main/java/gachon/jupoza/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/static/js/article-detail.js
  src/main/resources/static/js/article-form.js
  src/main/resources/static/js/article.js
  src/main/resources/static/js/demo/article-detail.js
  src/main/resources/templates/article-detail.html
  src/main/resources/templates/article-form.html
  src/main/resources/templates/article.html
Labels: documentation, enhancement

#50 #49 - 사이드바 리팩토링
  src/main/resources/static/js/sidebar.js
  src/main/resources/templates/article-detail.html
  src/main/resources/templates/article.html
  src/main/resources/templates/blank.html
  src/main/resources/templates/blank2.html
  src/main/resources/templates/blank3.html
  src/main/resources/templates/category.html
  src/main/resources/templates/my-portfolio.html
  src/main/resources/templates/portfolio.html
  src/main/resources/templates/stocklist.html
Labels: enhancement

#52 #51 - 내 포트폴리오 삭제기능 구현
  src/main/resources/static/js/my-portfolio.js
  src/main/resources/templates/my-portfolio.html
Labels: enhancement

#56 포트폴리오 뷰에 주식 5개를 가져올떄 버그픽스
  src/main/resources/static/js/portfolio.js
Labels: bug

#58 라이센스 추가
  LICENSE
Labels: enhancement
